// Proof planning, controller persistence, and deterministic WAAPI cleanup. Live motion is separately checked.
import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {games as classics,solitaire,solitaireFinishPlan,solitaireMove} from '../dist/games/classics.js';import {games as modern} from '../dist/games/modern.js';import {games as logic} from '../dist/games/logic.js';import {clone,button} from '../dist/games/core.js';import {commitDrag,installDragControls} from '../dist/drag.js';
const proofs=JSON.parse(fs.readFileSync(new URL('./solitaire-deal-solutions.json',import.meta.url)));
const source=fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8').replace(/^import .*;$/gm,'')+'\nglobalThis.inspect=()=>({saves,current,autoFinishPresentation,puzzleMotion,completedLevels});Object.assign(globalThis,{handle,persist,render,cancelPuzzleMotion});';
let checks=0;function test(name,fn){fn();checks++;console.log('PASS',name);}
function checkpoint(proof){const state=clone(proof.initial);for(const step of proof.solution){const before=clone(state);if(step.type==='stock')solitaire.action(state,'stock');else solitaireMove(state,step.from,step.to);if(solitaireFinishPlan(state))return{before,step,eligible:clone(state),plan:solitaireFinishPlan(state)};}throw Error('No finish checkpoint');}
function boot({store=new Map(),reduced=false,hash='#solitaire'}={}){let html='';const animations=[],events={},docEvents={},writes=[];
 class Node{constructor(){this.style={};this.children=[];this.dataset={};this.classList={add(){}};}setAttribute(){}removeAttribute(){}focus(){}getBoundingClientRect(){return{left:10,top:100,width:70,height:98,right:80,bottom:198};}appendChild(n){this.children.push(n);n.parent=this;}remove(){if(this.parent)this.parent.children=this.parent.children.filter(x=>x!==this);}set innerHTML(v){this.html=v;this.firstElementChild=new Node();}get innerHTML(){return this.html;}animate(frames,options){const a={frames,options,el:this,cancel(){this.canceled=true;this.oncancel?.();}};animations.push(a);return a;}}
 const board=new Node(),el=new Node(),app={get innerHTML(){return html},set innerHTML(v){html=v},addEventListener(){},querySelector:s=>s==='.solitaire-board'?board:el,querySelectorAll:()=>[]};
 const ctx={commitDrag,installDragControls,classics,modern,logic,clone,button,crypto,console,URLSearchParams,navigator:{webdriver:true},location:{hostname:'localhost',search:'?qa=1',hash},history:{pushState(){}},performance:{now:()=>0},localStorage:{getItem:k=>store.get(k),setItem:(k,v)=>{writes.push(k);store.set(k,v)}},matchMedia:()=>({matches:reduced}),document:{createElement:()=>new Node(),querySelector:()=>app,addEventListener:(k,f)=>docEvents[k]=f,activeElement:el,hidden:false,referrer:''},window:{addEventListener:(k,f)=>events[k]=f,scrollTo(){}},setInterval(){}};vm.createContext(ctx);vm.runInContext(source,ctx);return{ctx,store,app,animations,events,docEvents,writes,board};}
function trigger(t,proof=proofs[0]){const c=checkpoint(proof),r=t.ctx.inspect().saves.solitaire;r.state=clone(c.before);r.initial=clone(proof.initial);r.levelId=proof.id;r.packId='starter-v1';r.moves=40;r.history=[];r.autoMoves=0;r.autoSuppressed=false;r.finished=false;t.ctx.persist();if(c.step.type==='stock')t.ctx.handle('stock');else{t.ctx.handle('select',c.step.from);c.before=clone(r.state);t.ctx.handle(c.step.to[0]==='f'?'foundation':'column',c.step.to.split(':')[1]);}return{c,r};}
for(const p of proofs)test(`${p.id}: pure foundation-only proof is complete and never mutates its input`,()=>{const c=checkpoint(p),before=JSON.stringify(c.eligible),plan=solitaireFinishPlan(c.eligible);assert.equal(JSON.stringify(c.eligible),before);const copy=clone(c.eligible);for(const s of plan){assert(/^f:[0-3]$/.test(s.to));assert(solitaireMove(copy,s.from,s.to));}assert(solitaire.won(copy));assert.equal(plan.length,52-c.eligible.foundation.flat().length);});
test('All face-up alone is insufficient; stock, hidden cards, blocked rank order and corrupt decks reject',()=>{const c=checkpoint(proofs[0]);for(const kind of ['stock','hidden','blocked','duplicate']){const s=clone(c.eligible);if(kind==='stock'){s.stock.push(s.tableau.find(p=>p.length).pop());}if(kind==='hidden')s.tableau.find(p=>p.length)[0].up=false;if(kind==='duplicate'){const cards=s.tableau.flat();Object.assign(cards[1],cards[0]);}if(kind==='blocked'){s.tableau=Array.from({length:7},()=>[]);s.waste=Array.from({length:13},(_,i)=>({suit:0,rank:i+1,up:true}));s.foundation=Array.from({length:4},(_,suit)=>suit?Array.from({length:13},(_,i)=>({suit,rank:i+1,up:true})):[]);}assert.equal(solitaireFinishPlan(s),null,kind);}const s=clone(c.eligible),before=JSON.stringify(s);assert.equal(solitaire.applyFinish(s,[{from:'t:0:999',to:'f:0'}]),false);assert.equal(JSON.stringify(s),before);});
test('Atomic trigger counts one player move, separate automatic cards, one Undo and one earned level',()=>{const t=boot(),{c,r}=trigger(t);assert(solitaire.won(r.state));assert.equal(r.moves,41);assert.equal(r.autoMoves,c.plan.length);assert.equal(r.hints,0);assert.equal(r.history.length,1);assert(r.finished);assert(t.ctx.inspect().puzzleMotion);assert.doesNotMatch(t.app.innerHTML,/class="table-result"/);assert.match(t.app.innerHTML,/Auto-collecting/);const key='pocket-puzzle-qa-v1-completed:starter-v1:solitaire:test-01';assert.equal(t.writes.filter(k=>k===key).length,1);const final=JSON.stringify(r.state);t.ctx.handle('stock');assert.equal(JSON.stringify(r.state),final);assert.equal(r.moves,41);const scene=t.ctx.inspect().puzzleMotion;assert(scene.nodes.length===r.autoMoves);assert(t.animations.filter(a=>a.options.duration===230).every(a=>a.frames[0].opacity===0));t.animations.at(-1).onfinish();assert.equal(t.ctx.inspect().puzzleMotion,null);assert.match(t.app.innerHTML,/Level 1 complete/);t.ctx.handle('undo');assert.equal(JSON.stringify(r.state),JSON.stringify(c.before));assert.equal(r.moves,40);assert.equal(r.autoMoves,0);assert(r.autoSuppressed);assert.equal(t.writes.filter(k=>k===key).length,1);const u=boot({store:t.store,reduced:true});assert(!u.ctx.inspect().saves.solitaire.finished);assert.equal(JSON.stringify(u.ctx.inspect().saves.solitaire.state),JSON.stringify(c.before));});
test('Undo suppression ends after another successful player move and does not duplicate completion',()=>{const t=boot(),{c,r}=trigger(t);t.ctx.handle('undo');if(c.step.type==='stock')t.ctx.handle('stock');else{if(r.state.selected!==c.step.from)t.ctx.handle('select',c.step.from);t.ctx.handle(c.step.to[0]==='f'?'foundation':'column',c.step.to.split(':')[1]);}assert(solitaire.won(r.state));assert(!r.autoSuppressed);assert.equal(t.writes.filter(k=>k.includes('-completed:')).length,1);});
for(const action of ['undo','settings','help','pause','restart','new','home'])test(`Auto-finish interrupted by ${action} removes all transient cards and stale callbacks`,()=>{const t=boot(),{c,r}=trigger(t),scene=t.ctx.inspect().puzzleMotion,final=JSON.stringify(r.state);t.ctx.handle(action);assert.equal(t.ctx.inspect().puzzleMotion,null);assert.equal(t.ctx.inspect().autoFinishPresentation,null);assert.equal(t.board.children.length,0);assert.equal(JSON.stringify(r.state),action==='undo'?JSON.stringify(c.before):final);scene.finish();assert.equal(JSON.stringify(r.state),action==='undo'?JSON.stringify(c.before):final);});
for(const event of ['blur','resize','pagehide','hidden'])test(`Auto-finish ${event} reveals committed victory, reload never replays the collection`,()=>{const t=boot(),{r}=trigger(t),after=JSON.stringify(r.state);if(event==='hidden'){t.ctx.document.hidden=true;t.docEvents.visibilitychange();}else t.events[event]();assert.equal(t.ctx.inspect().puzzleMotion,null);assert.equal(t.ctx.inspect().autoFinishPresentation,null);assert.equal(JSON.stringify(r.state),after);const u=boot({store:t.store});assert.equal(JSON.stringify(u.ctx.inspect().saves.solitaire.state),after);assert.equal(u.animations.length,0);assert.match(u.app.innerHTML,/Level 1 complete/);});
test('Reduced motion reveals immediate committed result; eligible resumed states get an Undo boundary',()=>{const t=boot({reduced:true}),{r}=trigger(t);assert.equal(t.animations.length,0);assert.equal(t.ctx.inspect().autoFinishPresentation,null);assert.match(t.app.innerHTML,/Level 1 complete/);t.ctx.handle('undo');r.state=clone(checkpoint(proofs[0]).eligible);r.autoSuppressed=false;r.history=[];t.ctx.persist();const u=boot({store:t.store,reduced:true}),s=u.ctx.inspect().saves.solitaire;assert(s.finished);assert.equal(s.history.length,1);u.ctx.handle('undo');assert(!s.finished);assert(s.autoSuppressed);});
console.log(`AUTO FINISH TESTS PASSED (${checks})`);
