import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {games as classics,solitaire} from '../dist/games/classics.js';import {games as modern} from '../dist/games/modern.js';import {games as logic,sudokuSolve} from '../dist/games/logic.js';import {clone,button} from '../dist/games/core.js';import {commitDrag,installDragControls} from '../dist/drag.js';
const games=[...classics,...modern,...logic],proofs=JSON.parse(fs.readFileSync(new URL('./starter-pack-proofs.json',import.meta.url))),solProofs=JSON.parse(fs.readFileSync(new URL('./solitaire-deal-solutions.json',import.meta.url)));
const raw=fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');
const source=raw.replace(/^import .*;$/gm,'')+'\nglobalThis.inspect=()=>({saves,freeSaves,packRounds,activeModes,completedLevels,unsavedCompletions,current,confirmAction,settingsOpen,dealPickerOpen,pendingDeal,storageOK,notice,protectedPacks,autoFinishPresentation,puzzleMotion});Object.assign(globalThis,{handle,persist,render,nextLevel,nextToken,roundLevel,levelUnlocked,refreshLevelProgress,validState,cancelPuzzleMotion,animateAutoFinish});';
let count=0;function test(name,fn){fn();count++;console.log('PASS',name);}
export function boot({store=new Map(),hash='',deny=false,code=source}={}){let html='',time=0;const events={},writes=[];const el={dataset:{},focus(){}};const app={get innerHTML(){return html},set innerHTML(x){html=x},addEventListener(){},querySelector:()=>el,querySelectorAll:()=>[]};const ctx={commitDrag,installDragControls,classics,modern,logic,clone,button,crypto,console,URLSearchParams,navigator:{webdriver:true},location:{hostname:'localhost',search:'?qa=1',hash},history:{pushState(){}},performance:{now:()=>time},localStorage:{getItem:k=>store.get(k),setItem:(k,v)=>{if(typeof deny==='function'?deny(k):deny)throw Error('denied');writes.push(k);store.set(k,v)}},matchMedia:()=>({matches:true}),document:{querySelector:()=>app,addEventListener(){},activeElement:el,hidden:false,referrer:''},window:{addEventListener:(k,f)=>events[k]=f,scrollTo(){}},setInterval(){}};vm.createContext(ctx);vm.runInContext(code,ctx);return{ctx,store,events,app,writes,advance:n=>time+=n};}
function select(t,g,l){t.ctx.handle('levels');t.ctx.handle('choose-deal',l.id);t.ctx.handle('confirm');return t.ctx.inspect().saves[g.id];}
function solve(t,g,l){const r=t.ctx.inspect().saves[g.id],proof=g.id==='solitaire'?solProofs.find(x=>x.id===l.id).solution:proofs[g.id].find(x=>x.id===l.id).proof;
 for(const step of proof){if(g.id==='solitaire'){if(step.type==='stock')t.ctx.handle('stock');else{t.ctx.handle('select',step.from);t.ctx.handle(step.to[0]==='f'?'foundation':'column',step.to.split(':')[1]);}}else if(g.id==='mahjong'){t.ctx.handle('tile',step[0]);t.ctx.handle('tile',step[1]);}else if(g.id==='water'){t.ctx.handle('tube',step[0]);t.ctx.handle('tube',step[1]);}else if(g.id==='arrows')t.ctx.handle('arrow',step);else if(g.id==='sliding')t.ctx.handle('tile',step);else if(g.id==='words')t.ctx.handle('line',{start:step[0],end:step[1]});}
 if(g.id==='sudoku')for(let i=0;i<81;i++)if(!r.state.given[i]){t.ctx.handle('cell',i);t.ctx.handle('number',proof[i]);}
 assert(g.won(r.state),g.id+' '+l.id+' must win');assert(r.finished);return r;
}
for(const g of games.filter(g=>g.levels))test(`${g.title}: three proved levels, sequential Next, persistence and honest end`,()=>{const t=boot({hash:'#'+g.id});let r=t.ctx.inspect().saves[g.id];assert.equal(r.levelId,g.levels[0].id);assert.equal(t.ctx.inspect().activeModes[g.id],'levels');for(let n=0;n<3;n++){const l=g.levels[n];assert.equal(r.levelId,l.id);assert(t.ctx.validState(g.id,r.state));solve(t,g,l);const key='pocket-puzzle-qa-v1-completed:starter-v1:'+g.id+':'+l.id;assert.equal(t.store.get(key),'1');assert.equal(t.writes.filter(x=>x===key).length,1);const after=JSON.stringify(r.state);t.ctx.handle('undo');assert(!r.finished);assert.equal(t.store.get(key),'1');t.ctx.handle('restart');t.ctx.handle('confirm');r=t.ctx.inspect().saves[g.id];solve(t,g,l);assert.equal(t.writes.filter(x=>x===key).length,1);if(n<2){const token=t.ctx.nextToken(g,r,g.levels[n+1]);t.ctx.handle('next-level',token);r=t.ctx.inspect().saves[g.id];const id=r.runId;t.ctx.handle('next-level',token);assert.equal(t.ctx.inspect().saves[g.id].runId,id);assert.equal(r.levelId,g.levels[n+1].id);}else{assert.match(t.app.innerHTML,/Starter pack complete/);assert.doesNotMatch(t.app.innerHTML,/data-action="next-level"/);}}const reloaded=boot({store:t.store,hash:'#'+g.id});assert.equal(reloaded.ctx.inspect().saves[g.id].levelId,g.levels[2].id);assert.equal(reloaded.ctx.inspect().completedLevels.size,3);assert.equal(t.store.has('pocket-puzzle-v1'),false);});
test('Unfinished free-play round is kept across confirmed levels and return',()=>{const t=boot({hash:'#water'}),g=modern.find(x=>x.id==='water');t.ctx.handle('new');t.ctx.handle('confirm');const r=t.ctx.inspect().saves.water;assert.equal(t.ctx.inspect().activeModes.water,'free');t.ctx.handle('tube',r.state.path[0][0]);const state=JSON.stringify(r);t.ctx.handle('levels');t.ctx.handle('choose-deal','water-1');t.ctx.handle('cancel');t.ctx.handle('settings');assert.equal(JSON.stringify(t.ctx.inspect().saves.water),state);select(t,g,g.levels[0]);assert.equal(JSON.stringify(t.ctx.inspect().freeSaves.water),state);t.ctx.handle('levels');t.ctx.handle('choose-deal','free');t.ctx.handle('confirm');assert.equal(JSON.stringify(t.ctx.inspect().saves.water),state);});
test('Locked levels reject direct stale selection and mode pointers are validated',()=>{const t=boot({hash:'#water'}),r=t.ctx.inspect().saves.water;t.ctx.handle('levels');t.ctx.handle('choose-deal','water-3');assert.equal(t.ctx.inspect().confirmAction,null);assert.equal(t.ctx.inspect().saves.water.runId,r.runId);t.ctx.handle('settings');t.store.set('pocket-puzzle-qa-v1-play-mode:water','arbitrary');const u=boot({store:t.store,hash:'#water'});assert(['free','levels'].includes(u.ctx.inspect().activeModes.water));assert.notEqual(u.ctx.inspect().activeModes.water,'arbitrary');});
test('Schema-1 validation accepts new pack shapes and preserves original shapes',()=>{const t=boot();for(const g of games){assert(t.ctx.validState(g.id,g.create()));for(const l of g.levels||[])assert(t.ctx.validState(g.id,l.state));}const w=clone(proofs.water[0].state);w.tubes[0].push(4);assert(!t.ctx.validState('water',w));const m=clone(proofs.mahjong[1].state);m.tiles.push({...m.tiles[0]});assert(!t.ctx.validState('mahjong',m));});
test('New tabs reconcile pack progress and stale Next cannot skip a level',()=>{const store=new Map(),a=boot({store,hash:'#arrows'}),b=boot({store,hash:'#arrows'}),g=logic.find(g=>g.id==='arrows');let r=solve(a,g,g.levels[0]);const token=a.ctx.nextToken(g,r,g.levels[1]);a.ctx.handle('next-level',token);b.ctx.handle('next-level',token);assert.equal(a.ctx.inspect().saves.arrows.levelId,'arrows-2');assert.equal(b.ctx.inspect().saves.arrows.levelId,'arrows-2');assert.equal(a.ctx.inspect().saves.arrows.runId,b.ctx.inspect().saves.arrows.runId);});
test('Completion in another tab never changes an unfinished free-play slot',()=>{const store=new Map(),a=boot({store,hash:'#water'}),g=modern.find(g=>g.id==='water');a.ctx.handle('new');a.ctx.handle('confirm');const free=JSON.stringify(a.ctx.inspect().saves.water);select(a,g,g.levels[0]);solve(a,g,g.levels[0]);assert.equal(JSON.stringify(a.ctx.inspect().freeSaves.water),free);assert.equal(JSON.stringify(JSON.parse(store.get('pocket-puzzle-qa-v1')).saves.water),free);});
test('Denied storage retains in-session play but never claims durable level progress',()=>{const t=boot({hash:'#arrows',deny:true}),g=logic.find(g=>g.id==='arrows');solve(t,g,g.levels[0]);assert.equal(t.ctx.inspect().storageOK,false);assert(t.ctx.inspect().unsavedCompletions.size);assert.match(t.ctx.inspect().notice,/not saved/);assert.equal(t.store.size,0);});
test('Sudoku starter puzzles have exact clue counts and unique solutions',()=>{for(const [n,l]of proofs.sudoku.entries()){assert.equal(l.state.given.filter(Boolean).length,[46,39,32][n]);assert.equal(sudokuSolve(l.state.cells).count,1);}});
test('Timer-only remote pack updates preserve a locally pending board action',()=>{const store=new Map(),a=boot({store,hash:'#solitaire'}),b=boot({store,hash:'#solitaire'}),local=b.ctx.inspect().saves.solitaire;solitaire.action(local.state,'stock');local.moves++;const board=JSON.stringify(local.state);a.advance(1234);a.ctx.handle('pause');a.ctx.persist();b.ctx.persist();assert.equal(JSON.stringify(b.ctx.inspect().saves.solitaire.state),board);assert.equal(b.ctx.inspect().saves.solitaire.moves,1);assert.equal(b.ctx.inspect().saves.solitaire.activeMs,1234);});
test('Partial pack/mode write preserves both attempts and offers explicit resume after reload',()=>{let fail=false;const t=boot({hash:'#water',deny:k=>fail&&k.includes('-play-mode:')});t.ctx.handle('new');t.ctx.handle('confirm');const free=JSON.stringify(t.ctx.inspect().saves.water);fail=true;select(t,modern[0],modern[0].levels[0]);const pack=t.ctx.inspect().saves.water;assert(!t.ctx.inspect().storageOK);const u=boot({store:t.store,hash:'#water'});assert.equal(JSON.stringify(u.ctx.inspect().saves.water),free);u.ctx.handle('levels');assert.match(u.app.innerHTML,/Resume level attempt/);u.ctx.handle('choose-deal','levels');u.ctx.handle('confirm');assert.equal(u.ctx.inspect().saves.water.runId,pack.runId);assert.equal(JSON.stringify(u.ctx.inspect().freeSaves.water),free);assert.equal(t.store.get('pocket-puzzle-qa-v1-play-mode:water'),'levels');});
test('Failed completion writes recover once without duplicate credits',()=>{let fail=true;const t=boot({hash:'#arrows',deny:k=>fail&&k.includes('-completed:')}),g=logic.find(g=>g.id==='arrows');solve(t,g,g.levels[0]);const key=completionKeyFor(g,g.levels[0]);assert(!t.store.has(key));assert(t.ctx.inspect().unsavedCompletions.has(key));fail=false;t.ctx.persist();assert.equal(t.store.get(key),'1');assert(!t.ctx.inspect().unsavedCompletions.size);t.ctx.persist();assert.equal(t.writes.filter(k=>k===key).length,1);assert.equal(boot({store:t.store,hash:'#arrows'}).ctx.inspect().completedLevels.size,1);});
function completionKeyFor(g,l){return 'pocket-puzzle-qa-v1-completed:starter-v1:'+g.id+':'+l.id;}
test('Unreadable pack is protected without poisoning healthy free play or other packs',()=>{const key='pocket-puzzle-qa-v1-starter-round-v1:water',bad=JSON.stringify({schema:999,secret:'future level format'}),store=new Map([[key,bad]]),t=boot({store,hash:'#solitaire',deny:k=>k.includes('-recovery-')});t.ctx.handle('stock');assert.equal(t.ctx.inspect().saves.solitaire.moves,1);assert(t.ctx.inspect().storageOK);assert.equal(store.get(key),bad);assert(!t.ctx.inspect().protectedPacks.has('solitaire'));t.ctx.handle('open','water');t.ctx.handle('tube',0);assert.equal(store.get(key),bad);assert.match(t.app.innerHTML,/Saving is unavailable/);t.ctx.handle('new');t.ctx.handle('confirm');assert.equal(t.ctx.inspect().activeModes.water,'free');assert(t.ctx.inspect().storageOK);assert.equal(store.get(key),bad);assert(JSON.parse(store.get('pocket-puzzle-qa-v1')).saves.water);});
test('The actual shipped 1.10.1 controller cannot overwrite pack attempts or earned progress',()=>{const legacy=fs.readFileSync(new URL('./legacy-app-1.10.1.txt',import.meta.url),'utf8').replace(/^import .*;$/gm,'')+'\nglobalThis.inspect=()=>({saves,current});Object.assign(globalThis,{handle,persist});',store=new Map(),old=boot({store,hash:'#water',code:legacy});old.ctx.handle('tube',old.ctx.inspect().saves.water.state.path[0][0]);const newer=boot({store,hash:'#water'}),g=modern.find(g=>g.id==='water');assert.equal(newer.ctx.inspect().activeModes.water,'free');select(newer,g,g.levels[0]);solve(newer,g,g.levels[0]);const saved=new Map([...store].filter(([k])=>k.includes('-starter-round-')||k.includes('-completed:')||k.includes('-play-mode:')));old.ctx.handle('new');old.ctx.handle('confirm');old.ctx.persist();for(const [k,v]of saved)assert.equal(store.get(k),v);const u=boot({store,hash:'#water'});assert.equal(u.ctx.inspect().saves.water.levelId,'water-1');assert(u.ctx.inspect().saves.water.finished);assert(u.ctx.inspect().freeSaves.water);});
console.log(`PROGRESSION TESTS PASSED (${count})`);
