// Catalog proofs replay real public actions; UI/controller tests never inject a win.
import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {games as classics,solitaire,mahjong,mahjongGeometry,freeTile} from '../dist/games/classics.js';import {games as modern} from '../dist/games/modern.js';import {games as logic} from '../dist/games/logic.js';import {clone,button} from '../dist/games/core.js';import {commitDrag,installDragControls} from '../dist/drag.js';
const proofs=JSON.parse(fs.readFileSync(new URL('./solitaire-deal-solutions.json',import.meta.url),'utf8'));
let checks=0;function test(name,run){run();checks++;console.log('PASS',name);}
const source=fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8').replace(/^import .*;$/gm,'')+'\nglobalThis.inspect=()=>({saves,current,confirmAction,dealPickerOpen,pendingDeal,settingsOpen});Object.assign(globalThis,{handle,persist,render});';
function boot({store=new Map(),hash='#solitaire'}={}){let html='',time=0;const events={},el={dataset:{},focus(){}},app={get innerHTML(){return html},set innerHTML(v){html=v},addEventListener(){},querySelector:()=>el,querySelectorAll:()=>[]};const ctx={commitDrag,installDragControls,classics,modern,logic,clone,button,crypto,console,URLSearchParams,navigator:{webdriver:true},location:{hostname:'localhost',search:'?qa=1',hash},history:{pushState(){}},performance:{now:()=>time},localStorage:{getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)},matchMedia:()=>({matches:true}),document:{querySelector:()=>app,addEventListener(){},activeElement:el,hidden:false,referrer:''},window:{addEventListener:(k,f)=>events[k]=f,scrollTo(){}},setInterval(){}};vm.createContext(ctx);vm.runInContext(source,ctx);return{ctx,store,app,events,advance:n=>time+=n};}
function choose(t,id){t.ctx.handle('deals');t.ctx.handle('choose-deal',id);assert.equal(t.ctx.inspect().confirmAction,'deal');t.ctx.handle('confirm');}
for(const proof of proofs)test(`${proof.id}: distinct standard deck and every proof step reaches 52 foundations`,()=>{
 const catalog=solitaire.deals.find(d=>d.id===proof.id);assert.deepEqual(catalog.initial,proof.initial);assert.equal(proof.verification.difficultyProvisional,true);assert.equal(proof.verification.heuristicTrials,40);assert(!('solution'in catalog));const s=solitaire.createDeal(proof.id),cards=[...s.tableau.flat(),...s.stock];assert.equal(cards.length,52);assert.equal(new Set(cards.map(c=>c.suit+':'+c.rank)).size,52);assert.equal(s.stock.length,24);assert(s.stock.every(c=>!c.up));s.tableau.forEach((p,i)=>{assert.equal(p.length,i+1);assert(p.every((c,j)=>c.up===(i===j)));});
 for(const step of proof.solution){if(step.type==='stock')assert(solitaire.action(s,'stock',''));else{assert.equal(solitaire.action(s,'select',step.from),false);assert.equal(s.selected,step.from);assert(solitaire.action(s,step.to[0]==='f'?'foundation':'column',step.to.split(':')[1]));}}assert(solitaire.won(s));assert.equal(s.dealId,proof.id);
});
test('Catalog is fixed, isolated per round and has three distinct layouts',()=>{assert.equal(solitaire.deals.length,3);assert.equal(new Set(solitaire.deals.map(d=>JSON.stringify(d.initial))).size,3);const s=solitaire.createDeal('test-01');s.stock.pop();assert.equal(solitaire.createDeal('test-01').stock.length,24);assert.equal(solitaire.createDeal('missing'),null);assert(!solitaire.create().dealId);});
test('Opening, selecting and cancelling the picker preserves the entire random round',()=>{const t=boot();choose(t,'random');const r=t.ctx.inspect().saves.solitaire;t.ctx.handle('stock');const before=JSON.stringify(r);t.ctx.handle('deals');assert.match(t.app.innerHTML,/Level 1/);assert.match(t.app.innerHTML,/Difficulty labels are provisional/);assert(t.ctx.inspect().settingsOpen);t.ctx.handle('choose-deal','test-02');assert.match(t.app.innerHTML,/Your free-play round is kept/);assert.equal(JSON.stringify(r),before);t.ctx.handle('cancel');assert(t.ctx.inspect().dealPickerOpen);assert.equal(JSON.stringify(r),before);t.ctx.handle('settings');assert.equal(JSON.stringify(r),before);});
test('Confirmed test choice persists identity, keeps other games, and Restart replays exact deal',()=>{const t=boot();t.ctx.handle('open','water');const waterBefore=JSON.stringify(t.ctx.inspect().saves.water);t.ctx.handle('open','solitaire');choose(t,'test-02');let r=t.ctx.inspect().saves.solitaire;assert.equal(r.state.dealId,'test-02');assert.equal(r.moves,0);assert.match(t.app.innerHTML,/Level 2 \/ 3/);const initial=JSON.stringify(r.state);t.ctx.handle('stock');t.ctx.handle('restart');t.ctx.handle('confirm');r=t.ctx.inspect().saves.solitaire;assert.equal(JSON.stringify(r.state),initial);assert.equal(JSON.stringify(t.ctx.inspect().saves.water),waterBefore);const reload=boot({store:t.store});assert.equal(JSON.stringify(reload.ctx.inspect().saves.solitaire.state),initial);choose(t,'random');assert.equal(t.ctx.inspect().saves.solitaire.state.dealId,undefined);assert.equal(t.store.has('pocket-puzzle-v1'),false);});
test('Picker and confirmation gate board input, time and unsolicited choice dispatch',()=>{const t=boot(),r=t.ctx.inspect().saves.solitaire;t.ctx.handle('choose-deal','test-01');assert.equal(r.state.dealId,'test-01');t.ctx.handle('deals');const before=JSON.stringify(r.state);t.advance(9000);t.ctx.handle('stock');assert.equal(JSON.stringify(r.state),before);assert.equal(r.activeMs,0);t.ctx.handle('choose-deal','bad');assert.equal(t.ctx.inspect().confirmAction,null);t.ctx.handle('choose-deal','test-01');t.ctx.handle('stock');assert.equal(JSON.stringify(r.state),before);t.ctx.handle('cancel');t.ctx.handle('settings');assert.equal(r.activeMs,0);});
for(const proof of proofs)test(`${proof.id}: full controller victory, exact final Undo and replay`,()=>{const t=boot();choose(t,proof.id);const r=t.ctx.inspect().saves.solitaire;let before;for(const step of proof.solution){if(solitaire.won(r.state))break;before=JSON.stringify(r.state);if(step.type==='stock')t.ctx.handle('stock');else{t.ctx.handle('select',step.from);before=JSON.stringify(r.state);t.ctx.handle(step.to[0]==='f'?'foundation':'column',step.to.split(':')[1]);}}assert(solitaire.won(r.state));assert(r.finished);assert(r.moves<=proof.solution.length);assert(r.autoMoves>0);before=JSON.stringify(r.history.at(-1).state);assert.equal(r.hints,0);assert.match(t.app.innerHTML,/All 52 cards/);t.ctx.handle('undo');assert(!r.finished);assert.equal(JSON.stringify(r.state),before);t.ctx.handle('restart');t.ctx.handle('confirm');assert.deepEqual(JSON.parse(JSON.stringify(t.ctx.inspect().saves.solitaire.state)),solitaire.createDeal(proof.id));});
test('Cross-tab progress replaces a pending choice and prevents stale confirmation',()=>{const t=boot();choose(t,'random');t.ctx.handle('stock');t.ctx.handle('deals');t.ctx.handle('choose-deal','test-03');const data=JSON.parse(t.store.get('pocket-puzzle-qa-v1')),r=data.saves.solitaire;solitaire.action(r.state,'stock','');r.moves++;t.store.set('pocket-puzzle-qa-v1',JSON.stringify(data));t.ctx.handle('confirm');assert.equal(t.ctx.inspect().confirmAction,null);assert.equal(t.ctx.inspect().pendingDeal,null);assert(!t.ctx.inspect().saves.solitaire.state.dealId);assert.equal(t.ctx.inspect().saves.solitaire.moves,2);});
test('Tight portrait geometry preserves visible centers throughout 100 complete Mahjong routes',()=>{
 for(let n=0;n<100;n++){const s=mahjong.create(),g=mahjongGeometry(s);for(const [a,b]of s.solution){for(let i=0;i<s.tiles.length;i++){const t=s.tiles[i];if(t.gone)continue;const face=g.boxes[i],cx=face.left+face.width/2,cy=face.top+face.height/2;const covers=s.tiles.some((q,j)=>!q.gone&&q.z>t.z&&cx>g.boxes[j].left&&cx<g.boxes[j].left+g.boxes[j].width&&cy>g.boxes[j].top&&cy<g.boxes[j].top+g.boxes[j].height);assert.equal(covers,s.tiles.some(q=>!q.gone&&q.z>t.z&&q.x===t.x&&q.y===t.y));if(freeTile(s,i))assert(!covers);}assert(freeTile(s,a)&&freeTile(s,b));mahjong.action(s,'tile',a);assert(mahjong.action(s,'tile',b));}assert(mahjong.won(s));}
});
test('Win choice cancel preserves completion and result panel occupies the visible table',()=>{const t=boot();choose(t,'test-01');const r=t.ctx.inspect().saves.solitaire;for(const step of proofs[0].solution){if(step.type==='stock')t.ctx.handle('stock');else{t.ctx.handle('select',step.from);t.ctx.handle(step.to[0]==='f'?'foundation':'column',step.to.split(':')[1]);}}const before=JSON.stringify(r.state);t.ctx.handle('deals');t.ctx.handle('choose-deal','test-02');t.ctx.handle('cancel');t.ctx.handle('settings');assert(r.finished);assert.equal(JSON.stringify(r.state),before);assert.match(t.app.innerHTML,/id="win-title" tabindex="-1"/);const css=fs.readFileSync(new URL('../dist/style.css',import.meta.url),'utf8');assert(css.includes('.board-wrap.is-won .solitaire-scroll{display:none}'));assert(css.includes('max-height:100%;overflow-y:auto'));t.ctx.handle('undo');assert(!r.finished);assert.doesNotMatch(t.app.innerHTML,/class="table-result"/);});
console.log(`FIXED DEAL / PORTRAIT TESTS PASSED (${checks})`);
